### ISSUE TITLE
Not able to set the width and height

### ISSUE THREAD

**Issue by hotcakedev628** [XD2Sketch/react-oauth-popup#248]
I am trying to set the width and height for the popup to increase the default size, but I assume that the props are not working for now.

```
...
     <OauthPopup
        url={`${authDomain}/account/login`}
        onCode={login}
        onClose={onClose}
        height={500}
        title={"Login"}
        width={500}
      >
        <button>
          Login
        </button>
      </OauthPopup>
...
```

What is the reason why I can't set the custom size for the OAuth popup?

**Comment by kgoedecke** [comment]
@hotcakedev628 can you please specify which browser your using?
